### PR TITLE
Remove pre-cleanup step in the actions workflow

### PR DESCRIPTION
**Pull request by JohnnyLiu2886**
remove the process for removing the debian packages in the workflow file

### CODE REVIEW

**Review by utkarsh867 — CHANGES_REQUESTED** [review]
Change in github workflow does not warrant a change in the version of the apt package itself.

If you would like to think of it another way:
v2.1.0 and v2.1.1 would have no difference because github workflow is not present in the package itself. so apt would do nothing, even though it would change the version.

**Comment by utkarsh867** [comment]
The self-hosted runner now has the post-cleanup after each action.

**Comment by utkarsh867** [comment]
@JohnnyLiu2886 the [e4c1a66](https://github.com/clearbothk/px4_msgs/pull/3/commits/e4c1a66b7d019ae67ce3fe934a56a657880a14e8) commit needs to be removed.

**Comment by JohnnyLiu2886** [comment]
> @JohnnyLiu2886 the [e4c1a66](https://github.com/clearbothk/px4_msgs/pull/3/commits/e4c1a66b7d019ae67ce3fe934a56a657880a14e8) commit needs to be removed.

ok, it is removed

**Review by utkarsh867 — APPROVED** [review]

**Pull request merged**
